# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpbuilderatnightly < Formula
  desc ""
  homepage "https://cnoe.io"
  version "0.10.0-nightly.20250805"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250805/idpbuilder-darwin-amd64.tar.gz"
      sha256 "d751486461bbddbe45e28b4e145dc6859ef26a223ff69f06060842adbae24aa2"

      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250805/idpbuilder-darwin-arm64.tar.gz"
      sha256 "09ed8ab0ff75dbbb8f260340a9bbf8b0cf05f0c61e5ebd8874afe451cb1b2c2f"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250805/idpbuilder-linux-amd64.tar.gz"
      sha256 "91236a6ddf6b7a2a9ad4c39fd2836d9f19f37e2b391d83f9bd01085869cf21f8"
      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250805/idpbuilder-linux-arm64.tar.gz"
      sha256 "780fa80a1cc21156660cff68957f7db486daa3920ee70ae5289e6120b93f2831"
      def install
        bin.install "idpbuilder"
      end
    end
  end

  test do
    system "#{bin}/idpbuilder version"
  end
end
