# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdpbuilderNightly < Formula
  desc ""
  homepage "https://cnoe.io"
  version "0.11.0-nightly.20260629"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.11.0-nightly.20260629/idpbuilder-darwin-amd64.tar.gz"
      sha256 "5f4fdad42b20c31383ab0dcbc6910243c74fa8c94e1bdfc85ef75f703271f331"

      define_method(:install) do
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.11.0-nightly.20260629/idpbuilder-darwin-arm64.tar.gz"
      sha256 "2722db6ea33a0af0ece35508a4d6612c370bab4914d00f93633fb1f64d9bf82e"

      define_method(:install) do
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.11.0-nightly.20260629/idpbuilder-linux-amd64.tar.gz"
      sha256 "f167dba2741c2a991b66caa2410ecd435153ee6e5c7e4564e6fec1e20852bed9"
      define_method(:install) do
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.11.0-nightly.20260629/idpbuilder-linux-arm64.tar.gz"
      sha256 "70e002f67229a90ebb60cffe3c01c07893dfdc90ff19fd38901b713cd3f85ea6"
      define_method(:install) do
        bin.install "idpbuilder"
      end
    end
  end

  test do
    system "#{bin}/idpbuilder version"
  end
end
