# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdpbuilderAT0100Nightly20250317 < Formula
  desc ""
  homepage "https://cnoe.io"
  version "0.10.0-nightly.20250317"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250317/idpbuilder-darwin-amd64.tar.gz"
      sha256 "f066ef784916b3038270c4207ac28c32dcc6bf74b853e481d8034d72d24f627d"

      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250317/idpbuilder-darwin-arm64.tar.gz"
      sha256 "ee85fa6fba2fc491fd48e38b033a7b640f48ea7ca771447a543dfdca7aac626b"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250317/idpbuilder-linux-amd64.tar.gz"
        sha256 "b3e355c2dc51a66400659e7a84b605a8f6d97d3aa30b62bf660268087eb0d9e1"

        def install
          bin.install "idpbuilder"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250317/idpbuilder-linux-arm64.tar.gz"
        sha256 "401010c299abd992836364b91db84b0b2a0734c9be565ea57e61aa7530c5e8a7"

        def install
          bin.install "idpbuilder"
        end
      end
    end
  end

  test do
    system "#{bin}/idpbuilder --version"
  end
end
