# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpbuilder < Formula
  desc ""
  homepage "https://cnoe.io"
  version "0.10.0-nightly.20250402"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250402/idpbuilder-darwin-amd64.tar.gz"
      sha256 "29b73c5189986aa4447d21c87839d0a514e0205b56de50f1556318184688dc69"

      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250402/idpbuilder-darwin-arm64.tar.gz"
      sha256 "2f07ed7756475c137ca270f53a8c717367549fea2b8b43506a67651456123af4"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250402/idpbuilder-linux-amd64.tar.gz"
        sha256 "5e3d8d56c20acdcd52d9fee9eb31c654d48ed1110616abd26981d4d4af0b66cc"

        def install
          bin.install "idpbuilder"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250402/idpbuilder-linux-arm64.tar.gz"
        sha256 "05bb00bdeb41b1663531a3b2e145f652c328b8f6400125fabce482f27dcbf869"

        def install
          bin.install "idpbuilder"
        end
      end
    end
  end

  test do
    system "#{bin}/idpbuilder --version"
  end
end
