# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdpbuilderAT0100 < Formula
  desc ""
  homepage "https://cnoe.io"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0/idpbuilder-darwin-amd64.tar.gz"
      sha256 "d8cf6a71a50715f1dffa4c2df5df9e1b954ee9077c5dbd1cf0d8ea2b85753e6d"

      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0/idpbuilder-darwin-arm64.tar.gz"
      sha256 "03f93bfbad60807d8784d2bcc0e6bde8395ef2bd8c1c7362a50c74623756c040"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0/idpbuilder-linux-amd64.tar.gz"
      sha256 "644e4072d9ab566a49cda2fba7f32c02a16380774792922da50ed698430237bb"
      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0/idpbuilder-linux-arm64.tar.gz"
      sha256 "35a76c575db7fc810c6577e3f16f687705296ac73928931fbd74ada39dffd391"
      def install
        bin.install "idpbuilder"
      end
    end
  end

  test do
    system "#{bin}/idpbuilder version"
  end
end
