# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpbuilder < Formula
  desc ""
  homepage "https://cnoe.io"
  version "0.10.0-nightly.20250724"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250724/idpbuilder-darwin-amd64.tar.gz"
      sha256 "949968d7a68dfd5b8b0aec64f4ad0c2620b807ff21bea3dcda5f3a412e80116c"

      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250724/idpbuilder-darwin-arm64.tar.gz"
      sha256 "a2071bed2976d09dc60abbe402cf81a93e6d63536cb08c1e7d72da2d9d724945"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250724/idpbuilder-linux-amd64.tar.gz"
      sha256 "2981013a4dcc8d0580c94e00b706b40ace044f6825f599a0e922a3160e4f8eb6"
      def install
        bin.install "idpbuilder"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.0-nightly.20250724/idpbuilder-linux-arm64.tar.gz"
      sha256 "b10787899d1dc897a55d6a78e0a74a75e17e795b68b7a7a34e936681bec1335b"
      def install
        bin.install "idpbuilder"
      end
    end
  end

  test do
    system "#{bin}/idpbuilder --version"
  end
end
